### ISSUE TITLE
Add Bitcoin God

### ISSUE THREAD

**Issue by Ayms** [Ayms/bitcoin-transactions#17]
Code not available, waiting for answer from the team

**Comment by Ayms** [comment]
Done https://github.com/Ayms/bitcoin-transactions/commit/5451266b0af29854b51bc757c0cce8abfe3f7ec4

**Comment by Hastie38** [comment]
I sent bitcoin cash from blockchain wallet to another wallet. 
€150 and it says the address doesn't exist.
What should I do? This was 4 days ago still nothing in

**Comment by Ayms** [comment]
Why are you posting this on that bitcoin god issue? It seems like you used the tool to transfer bch from an address to another one, if so and it failed then please open another issue explaining what you did (without your private keys)

**Comment by Hastie38** [comment]
Is this no the bitcoin God? 
Thought you would be a le to help that's why I posted. Didnt know it wld be a problem

**Comment by Ayms** [comment]
Could you please explain what you did or are trying to do?
