### ISSUE TITLE
Tutorial to claim/move coins

### ISSUE THREAD

**Issue by Ayms** [Ayms/bitcoin-transactions#25]
Apparently it's not easy for people to retrieve the parameters to use the tool, especially they don't get that they have to find them and run the command for each transaction sending coins to the address they want to spend

If someone wants to do a video tuto for this, from installation to the commands

**Comment by maszfoloe2** [comment]
some problems I got:
1. why it always shows "bad transaction"
2. when I wanted to verify on web, it didn't want to load, I clicked submit many times but nothing happened.
3. Actually, how long the transaction verified? how long to get my btg on my wallet?
(please ignore my English) thanks.
