### ISSUE TITLE
How to use with an Electrum 2FA wallet

### ISSUE THREAD

**Issue by klaaspieter** [Ayms/bitcoin-transactions#38]
A long time ago I created an Electrum 2FA wallet and I have come to regret that decision. That out of the way how can I use this tool to get forked funds from my Electrum 2FA wallets?

For example I've tried creating a BTG transaction but always get the following error:

```
------------- End Check - deserialize
------------- Check - verify
Using BIP143 signing
Verifying signature for ...
********* - Bad transaction
```

**Comment by Ayms** [comment]
The logs do not say anything more (public key(s) does not match, etc ?)

I would need the command you used and the complete logs (without the private keys), you can email it to me if you like

**Comment by klaaspieter** [comment]
```
Removed because of comment below
```

I'd paste the output but I'm unsure which parts of the output are private. No indication of missing or mistmatched public key(s)...

**Comment by Ayms** [comment]
Did you check the keys and redeem script? Most likely if you get an error the keys/redeem script are/is not correct, you can use offline the browser version to check this quickly

Quasi everything is not really private with bitcoins, I would suggest that you email me the complete logs and the command (without private keys again), I am still (quite) busy with node-Tor but will take a look

**Comment by klaaspieter** [comment]
Eventually managed to figure out the right parameters to use with a lot of help from @Ayms (only to then discover the coins were already mysterously spent, but let's ignore that part 🤦‍♂ )

The final command I ended up using was (more details on the variables below):

```sh
node tx.js BTG create \
  prevtx=[previous transaction]\
  prevaddr=[previous address]\
  prevamount=[previous amount]\
  previndex=[previous index]\
  privkey=[priv key of first key]-[priv key of second key]-[redeem-script]-mofn\
  addr=[new address]\
  fees=[fees]
```

To get the values of `[previous transaction]`, `[priv key of first key]` and `[priv key of second key]` I followed [this tutorial](https://bitcointalk.org/index.php?topic=2550529) essentially up to the point where they start entering commands in the BTG Core console (the tutorial will also help you find the actual first and second public key).

The part that took me the most time was the exact format of privkey: `[priv key of first key]-[priv key of second key]-[redeem-script]-mofn\`. The order of keys doesn't matter, but everything between `[]` needs to be filled in.

**Comment by Ayms** [comment]
As we saw the BTG explorers are complete shxt, now a good tip for people to find the redeem scripts, associated keys and/or public keys is just to take a look at a transaction that has been already spent

In your case it was spent on BTC before BTG, by https://blockchain.info/tx/43d445fb753ee837093de79bf42b6b4b4d3c52ba7570d98cc85950c442a48a5f?format=hex

You copy this, decode the tx using https://peersm.com/wallets, get the redeem script, decode it via the tool also and then you get the corresponding public keys, then you must find the private keys in your wallet and you can check them again with the tool (offline)

Each time an output is spent the corresponding redeem script and/or public keys become public, then it's more simple to retrieve than using the tutorial
