### ISSUE TITLE
Feature request: Coin fork scanner

### ISSUE THREAD

**Issue by ewheelerinc** [Ayms/bitcoin-transactions#39]
Since you've already done the hard work of supporting so many coins, it would be neat to provide a BTC address containing coins and then scan them all at once to see what coins are available to be claimed.  Like this site, but I think `bitcoin-transactions` already supports more coins: https://findmycoins.ninja/

**Comment by Ayms** [comment]
That's a very different work requiring to scan the blockchains of all coins, which in addition is not so trivial, in the first versions of bitcoin transactions ninja was included, you can check previous versions
