### ISSUE TITLE
Test BCH

### ISSUE THREAD

**Issue by Ayms** [Ayms/bitcoin-transactions#4]
Volunteers welcome to test the tool for Bitcoin Cash

``node tx.js BCH <command> <params>``

**Comment by matmaer** [comment]
hi there, I'd like to help....

**Comment by Ayms** [comment]
Thanks but this is successfully tested now

Repo and examples updated, please see [example-4.js](https://github.com/Ayms/bitcoin-transactions/blob/master/example-4.js)

**Comment by 5-digits** [comment]
Is there any script to run bch on Tetsnet Network ?

**Comment by Ayms** [comment]
It works as it is if you change only the magic network number and port (to send the complete transaction to testnet, or you can just send the body transaction from a testnet explorer without modifying anything) using mainnet-like addresses

The complete modification in https://github.com/Ayms/bitcoin-transactions/blob/master/tx.js#L108-L123 is:

VERSION=2;
SIGHASH_FORKID=0x00000040;
FORKID_IN_USE=0;
MAIN=0xF4F3E5F4;
VERSION_='BCH'; //testnet
p2pk=new Buffer('6f','hex');
p2sh=new Buffer('c4','hex');
PRIV=new Buffer('ef','hex');
BIP143=true;
PORT=18333;
LASTBLOCK=500000;
PROTOCOL=70015;
NOSEGWIT.push('m');
NOSEGWIT.push('q');
BECH32.push('q');
BECH32.push('p');

**Comment by 5-digits** [comment]
I mean how to generate ( BCH testnet address) also pass transaction throw it

**Comment by Ayms** [comment]
That's what I wrote above, what is not clear?

You can use ``node tx.js BCH create ...`` with mainnet addresses (that will be converted to testnet ones in the output of the command if you make the above modifications) or testnet addresses, and once you have the tx use ``node tx.js BCH send tx testnet_node``

To generate/convert addresses you can also use ``convert`` in https://github.com/Ayms/bitcoin-wallets (using new Buffer('6f','hex') or new Buffer('c4','hex'))

**Comment by 5-digits** [comment]
Ok thank you @Ayms  my issue resolved
