### ISSUE TITLE
Implement BCD

### ISSUE THREAD

**Issue by Ayms** [Ayms/bitcoin-transactions#6]
Ongoing

**Comment by Ayms** [comment]
https://github.com/eveybcd/BitcoinDiamond/issues/2

**Comment by Ayms** [comment]
https://github.com/Ayms/bitcoin-transactions/commit/43624b7b2c2208cb7e2ad5232743a43463902b4b

Implementation of the "1 BTC to 10 BCD" trick, ie decimals changed from 8 to 7

**Comment by Ayms** [comment]
https://github.com/Ayms/bitcoin-transactions/commit/a2a0afb3aff999589ae0c4412443364ecb0c5f16

Implementation of the ``preblockhash`` [trick](https://github.com/eveybcd/BitcoinDiamond/issues/2#issuecomment-360161344)

Needs to be tested on the network

**Comment by Ayms** [comment]
https://github.com/Ayms/bitcoin-transactions/commit/cb1deaf3c19ba0290629d28fb6fe22232fc34ad4

Tested, closing

**Comment by matmaer** [comment]
thanks!
